# Generated by Django 4.2.4 on 2023-09-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBibCircular', '0003_alter_evento_descripcion_alter_libro_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('importe', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name_plural': 'Lectores'},
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.AddField(
            model_name='ventas',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.lector'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.libro'),
        ),
    ]
