# Generated by Django 4.2.4 on 2023-09-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBibCircular', '0004_ventas_alter_lector_options_libro_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.categoria'),
        ),
    ]
