# Generated by Django 4.2.4 on 2023-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBibCircular', '0006_libro_disponible_libro_vendedor_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
