# Generated by Django 4.2.4 on 2023-09-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBibCircular', '0007_libro_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='lector',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
