# Generated by Django 4.2.4 on 2023-09-22 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBibCircular', '0008_alter_ventas_options_lector_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.libro'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.categoria'),
        ),
    ]
