# Generated by Django 4.2.4 on 2023-09-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBibCircular', '0009_comentario_user_alter_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBibCircular.libro')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
