# Generated by Django 4.2.4 on 2023-09-26 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBibCircular', '0010_reserva_delete_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='lector',
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
