# Generated by Django 4.2.4 on 2023-09-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBibCircular', '0011_remove_reserva_lector_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppBibCircular.libro'),
        ),
    ]
